name: Package addon

on:
  push:
    tags:
      - '**'

jobs:
  build:
    if: ${{ !contains(github.ref_name, 'alpha') && !contains(github.ref_name, 'beta') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: packager

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
